### ISSUE TITLE
References?

### ISSUE THREAD

**Issue by aequasi** [izatop/mongot#2]
Are references possible with this lib?

**Comment by izatop** [comment]
@aequasi what do you mean? DBRef or program relations?

**Comment by aequasi** [comment]
DBRef, sorry that was fairly vague. Was to excited about a non-AR ODM haha

**Comment by izatop** [comment]
@aequasi i may add this feature at closest time if you really need it. But, what do you think about abstraction for $lookup instead dbref and classic relations?

**Comment by aequasi** [comment]
Havent actually read about `$lookup`. Looks like its supported from 3.2 and up? Is that ok with you? Looks way better than using a dbref

**Comment by izatop** [comment]
@aequasi yep, mongodb supports `$lookup` from 3.2 and this feature really faster than direct fetching data in classic way. But it may be hard a lot to code. However i'll add `DBRef` support for mongot.

**Comment by aequasi** [comment]
Would definitely love to see $lookup support, but dont need it asap

**Comment by izatop** [comment]
@aequasi let's talk about `DBRef`. What do you think how it should working? Should DBRef fetched automatically or in async maner?

```typescript
const doc = await OrderCollection.findOne({_id});

// fetch it automatic somewhere in internal
doc.user // available at one moment with its parent

// fetch by reference
const user = await doc.user.fetch()

// fetch by populate pattern
await doc.populate();
doc.user // available now
```

Or we could control it via decorators like this:

```typescript
class Doc extends SchemaDocument {
    @ref({fetch: 'auto'})
    user: User;
}```

**Comment by aequasi** [comment]
Could be done a couple ways. I like the decorator control. Thats handy.

Maybe also:

```typescript
const doc = await OrderCollection.findOne({_id}, {populate: false});

doc.user // undefined;
```
