### ISSUE TITLE
null _id from findOneAndUpdate

### ISSUE THREAD

**Issue by cryptiklemur** [izatop/mongot#3]
heh, srry for another issue...

Getting a `null` `_id` field on insert. Makes me wonder though. I've got a unique field in my database already. Any way i can use that value in the `_id` field? I'd try, but `_id` is `readonly`

**Comment by aequasi** [comment]
Or even maybe not have `_id` on the interface? My subdocuments have that, and its kinda annoying lol

**Comment by izatop** [comment]
@aequasi don't apologize, how are you getting `_id` after insert?

Insert op affects on a document and (again) tests are passes :)

```typescript
const doc = collection.factory({})
const insertResult = collection.insert(doc);
console.log(doc._id === insertResult.ref._id) // true
```

You can't change `_id` value and its type for instance of a document because it should be immutable (i think it should be). But i'll try to help you if you tell me how you store `_id` in your database: as ObjectID or some other type? I have case when we needed translate MySQL autoincrement id from tbales to Mongo collections.

P.S. If you try to get upserted document from findAndModify command you may know that Mongo doesn't return upserted [document by default](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#findOneAndUpdate).

**Comment by izatop** [comment]
> My subdocuments have that, and its kinda annoying lol

How do you declare subdocuments in schema?

**Comment by izatop** [comment]
Woops, I think I misunderstood. Can you explain op with except and actually get? If you except upserted `_id` for `findOneAndUpdate` helper you [should use](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#~findAndModifyWriteOpResult) `lastErrorObject` in `FindAndModifyResult` object returned by `findOneAndUpdate` to get it.

**Comment by aequasi** [comment]
![image](https://user-images.githubusercontent.com/896295/29894672-fe2d9bfa-8d8a-11e7-9075-382589193601.png)

I'm getting a null `_id` in the database

**Comment by aequasi** [comment]
I would much rather use `id` as my `_id` field too

**Comment by izatop** [comment]
Wow, how did you do it? It should be generated automatically. Don't answer, you passing _id as null? I think you really dig my library))

**Comment by aequasi** [comment]
I can't set _id, as its readonly, so im not passing it at all

```typescript
            const cls = this.collection.factory(data);
            await this.manager.doInitialize(cls, data); // Sets all the properties i have on the class(except _id, cause it can't set that. I tried setting it to my unique `id` field

            delete cls.kernel;
            const result = await this.collection.findOneAndUpdate({id: data.id}, cls, {upsert: true});
            cls.kernel   = this.kernel;

            return result.get() as T;
```

**Comment by aequasi** [comment]
Heres the library: https://github.com/aequasi/Distrocord

Heres the models: https://github.com/aequasi/Distrocord/tree/master/src/Model
Heres the logic that saves the data: https://github.com/aequasi/Distrocord/blob/master/src/Manager/Manager.ts#L15-L29

**Comment by izatop** [comment]
@aequasi i think i understand how it happens. Just try next release `mongot@1.4.15` ;(

**Comment by izatop** [comment]
I think i must rewrite my tests 😄

**Comment by izatop** [comment]
@aequasi what's with this issue? Can i close it?

**Comment by aequasi** [comment]
Sorry, project got backburnered. I'll give it a spin again this weekend.

**Comment by izatop** [comment]
I think it was fixed.
